Vidley2/ViewModels/StaffAddressViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidley2.Models;
namespace Vidley2.ViewModels
{
    public class StaffAddressViewModel
    {
        public int StaffAddressId { get; set; }
        public StaffAddress StaffAddress { get; set; }
        public IEnumerable<AddressType> AddressTypes { get; set; }
    }
}

Vidley2/Controllers/StaffAddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidley2.Models;
using Vidley2.ViewModels;
using System.Data.Entity;

namespace Vidley2.Controllers
{
    [Authorize]
    public class StaffAddressController : Controller
    {
        private ApplicationDbContext _context;
        public StaffAddressController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: StaffAddress
        public ActionResult Index()
        {
            var customerAddress = _context.CustomerAddress;
            //.Include(c => c.MembershipType).ToList()
            return View(customerAddress);
        }
        public ActionResult StaffAddressForm(int staffId)
        {
            var viewModel = new StaffAddressViewModel
            {
                StaffAddress = new StaffAddress()
                {
                    StaffId = staffId,
                },
                AddressTypes = _context.AddressTypes.ToList()
            };
            return View("StaffAddressForm", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(StaffAddress staffAddress)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new StaffAddressViewModel
                {
                    StaffAddress = staffAddress,
                    AddressTypes = _context.AddressTypes.ToList()
                };
                return View("StaffAddressForm", viewModel);
            }
            if (staffAddress.Id == 0)
                _context.StaffAddresses.Add(staffAddress);

            else
            {
                var staffAddressInDb = _context.CustomerAddress.Single(m => m.Id == staffAddress.Id);
                staffAddressInDb.AddressTypeId = staffAddress.AddressTypeId;
                staffAddressInDb.StreetAddress = staffAddress.StreetAddress;
                staffAddressInDb.Address2 = staffAddress.Address2;
                staffAddressInDb.City = staffAddress.City;
                staffAddressInDb.State = staffAddress.State;
                staffAddressInDb.ZipCode = staffAddress.ZipCode;
            }
            _context.SaveChanges();
            return RedirectToAction("Details", "Staff", new { id = staffAddress.StaffId });
        }
        public ActionResult Edit(int id)
        {
            var staffAddress = _context.StaffAddresses.SingleOrDefault(c => c.Id == id);
            if (staffAddress == null)
                return HttpNotFound();
            var viewModel = new StaffAddressViewModel
            {
                StaffAddress = staffAddress,
                AddressTypes = _context.AddressTypes.ToList()
            };

            return View("StaffAddressForm", viewModel);
        }
        public ActionResult Delete(int id)
        {
            var staffAddress = _context.StaffAddresses.Include(x => x.AddressType).SingleOrDefault(m => m.Id == id);
            if (staffAddress == null)
                return HttpNotFound();
            var viewModel = new StaffAddressViewModel
            {
                StaffAddressId = id,
                StaffAddress = staffAddress,
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(int StaffAddressId)
        {
            var staffAddress = _context.StaffAddresses.SingleOrDefault(m => m.Id == StaffAddressId);
            _context.StaffAddresses.Remove(staffAddress);

            _context.SaveChanges();

            return RedirectToAction("Details", "Staff", new { id = staffAddress.StaffId });
        }
    }
}

Vidley2/Views/StaffAddress/Delete.cshtml
@model Vidley2.ViewModels.StaffAddressViewModel
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Are you sure you want to delete?</h2>
@using (Html.BeginForm("DeleteConfirm", "StaffAddress"))
{
    @Html.HiddenFor(m => m.StaffAddressId)
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.AddressTypeId)
        <p>@Model.StaffAddress.AddressType.Type</p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.StreetAddress)
        <p>@Model.StaffAddress.StreetAddress </p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.Address2)
        <p>@Model.StaffAddress.Address2 </p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.City)
        <p>@Model.StaffAddress.City </p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.State)
        <p>@Model.StaffAddress.State </p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.ZipCode)
        <p>@Model.StaffAddress.ZipCode </p>
    </div>
    @Html.AntiForgeryToken()
    <button type="submit" class="btn-danger">Delete</button>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Vidley2/Views/StaffAddress/StaffAddressForm.cshtml
@model Vidley2.ViewModels.StaffAddressViewModel
@{
    ViewBag.Title = "StaffAddressForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New Address to Staff</h2>

@using (Html.BeginForm("Save", "StaffAddress"))
{
    @Html.HiddenFor(m => m.StaffAddress.Id)
    @Html.HiddenFor(m => m.StaffAddress.StaffId)
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.AddressTypeId)
        @Html.DropDownListFor(m => m.StaffAddress.AddressTypeId, new SelectList(Model.AddressTypes, "Id", "Type"), "Select Address Type", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.StaffAddress.AddressTypeId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.StreetAddress)
        @Html.TextBoxFor(m => m.StaffAddress.StreetAddress, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.Address2)
        @Html.TextBoxFor(m => m.StaffAddress.Address2, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.City)
        @Html.TextBoxFor(m => m.StaffAddress.City, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.State)
        @Html.TextBoxFor(m => m.StaffAddress.State, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffAddress.ZipCode)
        @Html.TextBoxFor(m => m.StaffAddress.ZipCode, new { @class = "form-control" })
    </div>
    @Html.AntiForgeryToken()
    <button type="submit" class="btn-primary">Save</button>
}