Vidley2/Models/StaffPhoneNumber.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidley2.Models
{
    public class StaffPhoneNumber
    {
        public int Id { get; set; }
        public Staff Staff { get; set; }
        public int StaffId { get; set; }
        public PhoneNumberType PhoneNumberType { get; set; }
        public int PhoneNumberTypeId { get; set; }
        public string PhoneNumber { get; set; }
        public int PhoneExtension { get; set; }
    }
}

Vidley2/Controllers/StaffPhoneNumberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidley2.Models;
using Vidley2.ViewModels;
using System.Data.Entity;

namespace Vidley2.Controllers
{
    [Authorize]
    public class StaffPhoneNumberController : Controller
    {
        private ApplicationDbContext _context;
        public StaffPhoneNumberController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: StaffPhoneNumber
        
        public ActionResult Index()
        {
            var staffPhoneNumber = _context.StaffPhoneNumbers;
            //.Include(c => c.MembershipType).ToList()
            return View(staffPhoneNumber);
        }
        public ActionResult StaffPhoneNumberForm(int staffId)
        {
            var viewModel = new StaffPhoneNumberFormViewModel
            {
                StaffPhoneNumber = new StaffPhoneNumber()
                {
                    StaffId = staffId,
                },
                PhoneNumberTypes = _context.PhoneNumberTypes.ToList()
            };
            return View("StaffPhoneNumberForm", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(StaffPhoneNumber staffPhoneNumber)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new StaffPhoneNumberFormViewModel
                {
                    StaffPhoneNumber = staffPhoneNumber,
                    PhoneNumberTypes = _context.PhoneNumberTypes.ToList()
                };
                return View("StaffPhoneNumberForm", viewModel);
            }
            if (staffPhoneNumber.Id == 0)
                _context.StaffPhoneNumbers.Add(staffPhoneNumber);

            else
            {
                var staffPhoneNumberInDb = _context.StaffPhoneNumbers.Single(m => m.Id == staffPhoneNumber.Id);
                staffPhoneNumberInDb.PhoneNumberTypeId = staffPhoneNumber.PhoneNumberTypeId;
                staffPhoneNumberInDb.PhoneNumber = staffPhoneNumber.PhoneNumber;
                staffPhoneNumberInDb.PhoneExtension = staffPhoneNumber.PhoneExtension;
            }
            _context.SaveChanges();
            return RedirectToAction("Details", "Staff", new { id = staffPhoneNumber.StaffId });
        }
        public ActionResult Edit(int id)
        {
            var staffPhoneNumber = _context.StaffPhoneNumbers.SingleOrDefault(c => c.Id == id);
            if (staffPhoneNumber == null)
                return HttpNotFound();
            var viewModel = new StaffPhoneNumberFormViewModel
            {
                StaffPhoneNumber = staffPhoneNumber,
                PhoneNumberTypes = _context.PhoneNumberTypes.ToList()
            };

            return View("StaffPhoneNumberForm", viewModel);
        }
        public ActionResult Delete(int id)
        {
            var staffPhoneNumber = _context.StaffPhoneNumbers.Include(x => x.PhoneNumberType).SingleOrDefault(m => m.Id == id);
            if (staffPhoneNumber == null)
                return HttpNotFound();
            var viewModel = new StaffPhoneNumberFormViewModel
            {
               StaffPhoneNumberId = id,
               StaffPhoneNumber = staffPhoneNumber,
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(int StaffPhoneNumberId)
        {
            var staffPhoneNumber = _context.StaffPhoneNumbers.SingleOrDefault(m => m.Id == StaffPhoneNumberId);
            _context.StaffPhoneNumbers.Remove(staffPhoneNumber);

            _context.SaveChanges();

            return RedirectToAction("Details", "Staff", new { id = staffPhoneNumber.StaffId });
        }
    }
}

Vidley2/Views/StaffPhoneNumber/Delete.cshtml
@model Vidley2.ViewModels.StaffPhoneNumberFormViewModel
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Are you sure you want to delete?</h2>
@using (Html.BeginForm("DeleteConfirm", "StaffPhoneNumber"))
{
    @Html.HiddenFor(m => m.StaffPhoneNumberId)
    <div class="form-group">
        @Html.LabelFor(m => m.StaffPhoneNumber.PhoneNumberTypeId)
        <p>@Model.StaffPhoneNumber.PhoneNumberType.Type</p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffPhoneNumber.PhoneNumber)
        <p>@Model.StaffPhoneNumber.PhoneNumber</p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffPhoneNumber.PhoneExtension)
        <p>@Model.StaffPhoneNumber.PhoneExtension</p>
    </div>
    @Html.AntiForgeryToken()
    <button type="submit" class="btn-primary">Delete</button>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Vidley2/Views/StaffPhoneNumber/StaffPhoneNumberForm.cshtml
@model Vidley2.ViewModels.StaffPhoneNumberFormViewModel
@{
    ViewBag.Title = "StaffAddressForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New Phone Number to Staff</h2>

@using (Html.BeginForm("Save", "StaffPhoneNumber"))
{
    @Html.HiddenFor(m => m.StaffPhoneNumber.Id)
    @Html.HiddenFor(m => m.StaffPhoneNumber.StaffId)
    <div class="form-group">
        @Html.LabelFor(m => m.StaffPhoneNumber.PhoneNumberTypeId)
        @Html.DropDownListFor(m => m.StaffPhoneNumber.PhoneNumberTypeId, new SelectList(Model.PhoneNumberTypes, "Id", "Type"), "Select Phone Number Type", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.StaffPhoneNumber.PhoneNumberTypeId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffPhoneNumber.PhoneNumber)
        @Html.TextBoxFor(m => m.StaffPhoneNumber.PhoneNumber, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StaffPhoneNumber.PhoneExtension)
        @Html.TextBoxFor(m => m.StaffPhoneNumber.PhoneExtension, new { @class = "form-control" })
    </div>
    @Html.AntiForgeryToken()
    <button type="submit" class="btn-primary">Save</button>
}