Vidley2/Models/CustomerMovieRental.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidley2.Models
{
    public class CustomerMovieRental
    {
        public int Id { get; set; }
        public Customer Customer { get; set; }
        public int CustomerId { get; set; }
        public Movie Movies { get; set; }
        public int MovieId { get; set; }
        public DateTime Checkin { get; set; }
        public DateTime? Checkout { get; set; }
    }
}

Vidley2/ViewModels/CustomerMovieRentalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidley2.Models;

namespace Vidley2.ViewModels
{
    public class CustomerMovieRentalViewModel
    {
        public int CustomerMovieRentalId { get; set; }
        public CustomerMovieRental CustomerMovieRental { get; set; }
        public IEnumerable<Movie> Movies { get; set; }

    }
}

Vidley2/Controllers/CustomerMovieRentalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidley2.Models;
using System.Data.Entity;
using Vidley2.ViewModels;
namespace Vidley2.Controllers
{
    [Authorize]
    public class CustomerMovieRentalController : Controller
    {
        private ApplicationDbContext _context;
        public CustomerMovieRentalController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: CustomerMovie
       
        public ActionResult CustomerMovieRentalForm(int customerId)
        {
            var viewModel = new CustomerMovieRentalViewModel
            {
                CustomerMovieRental = new CustomerMovieRental()
                {
                    CustomerId = customerId,
                },
              Movies = _context.Movies.ToList()
            };
            return View("CustomerMovieRentalForm", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CustomerMovieRental customerMovieRental)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new CustomerMovieRentalViewModel
                {
                    CustomerMovieRental = customerMovieRental,
                    Movies = _context.Movies.ToList()
                };
                return View("CustomerMovieRentalForm", viewModel);
            }
            if (customerMovieRental.Id == 0)
                _context.CustomerMovieRentals.Add(customerMovieRental);

            else
            {
                var customerMovieRentalInDb = _context.CustomerMovieRentals.Single(m => m.Id == customerMovieRental.Id);
                customerMovieRentalInDb.CustomerId= customerMovieRental.CustomerId;
                customerMovieRentalInDb.MovieId = customerMovieRental.MovieId;
                customerMovieRentalInDb.Checkin = customerMovieRental.Checkin;
                customerMovieRentalInDb.Checkout = customerMovieRental.Checkout;
            }

            
            _context.SaveChanges();
            return RedirectToAction("Details", "Customers", new { id = customerMovieRental.CustomerId });
        }
        public ActionResult Edit(int id)
        {
            var customerMovieRental = _context.CustomerMovieRentals.SingleOrDefault(c => c.Id == id);
            if (customerMovieRental == null)
            {
                return HttpNotFound();
            }

            var viewModel = new CustomerMovieRentalViewModel
            {
                CustomerMovieRental = customerMovieRental,
                Movies = _context.Movies.ToList()
            };

            return View("CustomerMovieRentalForm", viewModel);
        }
        public ActionResult Delete(int id)
        {
            var customerMovieRental = _context.CustomerMovieRentals.Include(x => x.Movies).SingleOrDefault(m => m.Id == id);
            if (customerMovieRental == null)
                return HttpNotFound();
            var viewModel = new CustomerMovieRentalViewModel
            {
                CustomerMovieRentalId = id,
                CustomerMovieRental = customerMovieRental,
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(int CustomerMovieRentalId)
        {
            var customerMovieRental = _context.CustomerMovieRentals.SingleOrDefault(m => m.Id == CustomerMovieRentalId);
            _context.CustomerMovieRentals.Remove(customerMovieRental);

            _context.SaveChanges();

            return RedirectToAction("Details", "Customers", new { id = customerMovieRental.CustomerId });
        }
    }
}

Vidley2/Views/CustomerMovieRental/CustomerMovieRentalForm.cshtml
@model Vidley2.ViewModels.CustomerMovieRentalViewModel
@{
    ViewBag.Title = "Customer Movie Rental Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customer Movie Rental Form</h2>

@using (Html.BeginForm("Save", "CustomerMovieRental"))
{
    @Html.HiddenFor(m => m.CustomerMovieRental.Id)
    @Html.HiddenFor(m => m.CustomerMovieRental.CustomerId)
   
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerMovieRental.Movies)
        @Html.DropDownListFor(m => m.CustomerMovieRental.MovieId, new SelectList(Model.Movies, "Id", "Name"), "Select Movie", new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerMovieRental.Checkin)
        @Html.TextBoxFor(m => m.CustomerMovieRental.Checkin, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerMovieRental.Checkout)
        @Html.TextBoxFor(m => m.CustomerMovieRental.Checkout, new { @class = "form-control" })
    </div>
    @Html.AntiForgeryToken()
    <button type="submit" class="btn-primary">Save</button>
}

Vidley2/Views/CustomerMovieRental/Delete.cshtml
@model Vidley2.ViewModels.CustomerMovieRentalViewModel
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Are you sure you want to Delete?</h2>


@using (Html.BeginForm("DeleteConfirm", "CustomerMovieRental"))
{
    @Html.HiddenFor(m => m.CustomerMovieRental.Id)
    @Html.HiddenFor(m=>m.CustomerMovieRentalId)
    @Html.HiddenFor(m => m.CustomerMovieRental.CustomerId)

    <div class="form-group">
        @Html.LabelFor(m => m.CustomerMovieRental.Movies)
        <p>@Model.CustomerMovieRental.Movies.Name</p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerMovieRental.Checkin)
        <p>@Model.CustomerMovieRental.Checkin</p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerMovieRental.Checkout)
        <p>@Model.CustomerMovieRental.Checkin</p>

    </div>
    @Html.AntiForgeryToken()
    <button type="submit" class="btn-danger">Delete</button>
}

Vidley2/Views/CustomerMovieRental/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>