Vidley2/ViewModels/CustomerAddressViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidley2.Models;
namespace Vidley2.ViewModels
{
    public class CustomerAddressViewModel
    {
        public int CustomerAddressId { get; set; }
        public CustomerAddress CustomerAddress { get; set; }
        public IEnumerable<AddressType> AddressTypes { get; set; }
    }
}

Vidley2/Controllers/CustomerAddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidley2.Models;
using Vidley2.ViewModels;
using System.Data.Entity;

namespace Vidley2.Controllers
{
    [Authorize]
    public class CustomerAddressController : Controller
    {
        // GET: CustomerAddress
        private ApplicationDbContext _context;
        public CustomerAddressController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: CustomerPhoneNumber
        public ActionResult Index()
        {
            var customerAddress = _context.CustomerAddress;
            //.Include(c => c.MembershipType).ToList()
            return View(customerAddress);
        }
        public ActionResult CustomerAddressForm(int customerId)
        {
            var viewModel = new CustomerAddressViewModel
            {
                CustomerAddress = new CustomerAddress()
                {
                    CustomerId = customerId,
                },
                AddressTypes = _context.AddressTypes.ToList()
            };
            return View("CustomerAddressForm", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CustomerAddress customerAddress)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new CustomerAddressViewModel
                {
                    CustomerAddress = customerAddress,
                    AddressTypes = _context.AddressTypes.ToList()
                };
                return View("CustomerAddressForm", viewModel);
            }
            if (customerAddress.Id == 0)
                _context.CustomerAddress.Add(customerAddress);

            else
            {
                var customerAddressInDb = _context.CustomerAddress.Single(m => m.Id == customerAddress.Id);
                customerAddressInDb.AddressTypeId = customerAddress.AddressTypeId;
                customerAddressInDb.StreetAddress = customerAddress.StreetAddress;
                customerAddressInDb.Address2 = customerAddress.Address2;
                customerAddressInDb.City = customerAddress.City;
                customerAddressInDb.State = customerAddress.State;
                customerAddressInDb.ZipCode = customerAddress.ZipCode;
            }
            _context.SaveChanges();
            return RedirectToAction("Details", "Customers", new { id = customerAddress.CustomerId });
        }
        public ActionResult Edit(int id)
        {
            var customerAddress = _context.CustomerAddress.SingleOrDefault(c => c.Id == id);
            if (customerAddress == null)
                return HttpNotFound();
            var viewModel = new CustomerAddressViewModel
            {
                CustomerAddress = customerAddress,
                AddressTypes = _context.AddressTypes.ToList()
            };

            return View("CustomerAddressForm", viewModel);
        }
        public ActionResult Delete(int id)
        {
            var customerAddress = _context.CustomerAddress.Include(x => x.AddressType).SingleOrDefault(m => m.Id == id);
            if (customerAddress == null)
                return HttpNotFound();
            var viewModel = new CustomerAddressViewModel
            {
                CustomerAddressId = id,
                CustomerAddress = customerAddress,
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(int CustomerAddressId)
        {
            var customerAddress = _context.CustomerAddress.SingleOrDefault(m => m.Id == CustomerAddressId);
            _context.CustomerAddress.Remove(customerAddress);

            _context.SaveChanges();

            return RedirectToAction("Details", "Customers", new { id = customerAddress.CustomerId });
        }
    }
}

Vidley2/Views/CustomerAddress/CustomerAddressForm.cshtml
@model Vidley2.ViewModels.CustomerAddressViewModel
@{
    ViewBag.Title = "Customer Address Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New Address to Customer</h2>

@using (Html.BeginForm("Save", "CustomerAddress"))
{
    @Html.HiddenFor(m => m.CustomerAddress.Id)
    @Html.HiddenFor(m => m.CustomerAddress.CustomerId)
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.AddressTypeId)
        @Html.DropDownListFor(m => m.CustomerAddress.AddressTypeId, new SelectList(Model.AddressTypes, "Id", "Type"), "Select Address Type", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CustomerAddress.AddressTypeId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.StreetAddress)
        @Html.TextBoxFor(m => m.CustomerAddress.StreetAddress, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.Address2)
        @Html.TextBoxFor(m => m.CustomerAddress.Address2, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.City)
        @Html.TextBoxFor(m => m.CustomerAddress.City, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.State)
        @Html.TextBoxFor(m => m.CustomerAddress.State, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.ZipCode)
        @Html.TextBoxFor(m => m.CustomerAddress.ZipCode, new { @class = "form-control" })
    </div>
    @Html.AntiForgeryToken()
    <button type="submit" class="btn-primary">Save</button>
}

Vidley2/Views/CustomerAddress/Delete.cshtml
@model Vidley2.ViewModels.CustomerAddressViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Are you sure you want to delete?</h2>
@using (Html.BeginForm("DeleteConfirm", "CustomerAddress"))
{
    @Html.HiddenFor(m => m.CustomerAddress.Id)
    @Html.HiddenFor(m => m.CustomerAddress.CustomerId)
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.AddressTypeId)
        <p>@Model.CustomerAddress.AddressType.Type</p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.StreetAddress)
        <p>@Model.CustomerAddress.StreetAddress </p>
</div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.Address2)
        <p>@Model.CustomerAddress.Address2 </p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.City)
        <p>@Model.CustomerAddress.City </p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.State)
        <p>@Model.CustomerAddress.State </p>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CustomerAddress.ZipCode)
        <p>@Model.CustomerAddress.ZipCode </p>
    </div>
    @Html.AntiForgeryToken()
    <button type="submit" class="btn-danger">Delete</button>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}